name: Gradle Build

on:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        java-package: jdk
        distribution: corretto

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-read-only: false

    - name: Build with Gradle
      run: ./gradlew build publishToMavenLocal

    - name: Install JBang
      run: |
        curl -Ls https://sh.jbang.dev | bash -s - app setup
        echo "${HOME}/.jbang/bin" >> $GITHUB_PATH

    - name: Run test scripts
      run: ./test-scripts.sh
